### ISSUE TITLE
No functions found in the repository

### ISSUE THREAD

**Issue by ruixuan-ray-zhang** [VITA-Group/TinT#3]
I would like to reproduce the results from the baseline models. However, it doesn't seem to have functions named checb_polinomial and evaluate_on_test_mstgcn in the entire repository, which should appear in graph_baselines/lib/utils.py. Could you help me out with that? Thanks!

    from lib.utils import scaled_Laplacian, cheb_polynomial
    from lib.utils import load_graphdata_channel1, get_adjacency_matrix, evaluate_on_test_mstgcn, compute_val_loss_mstgcn, predict_and_save_results_mstgcn

**Comment by ruixuan-ray-zhang** [comment]
I think I found the functions, but they are from the other repository. See link https://github.com/guoshnBJTU/ASTGCN-r-pytorch/blob/master/lib/utils.py

**Comment by Wenqing-Zheng** [comment]
Hi,

Thank you for pointing that out. We are sorry for the missing functions. This might due to we accidentally removed it in the version check before uploading the repo. We've just fixed it. You were correct in finding those functions' original repo.

Thank you again.
